# Generated by Django 2.1 on 2023-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='轮播图标题')),
                ('link', models.CharField(max_length=500, verbose_name='轮播图链接')),
                ('img_url', models.CharField(max_length=255, verbose_name='轮播图地址')),
                ('remark', models.TextField(verbose_name='轮播图备注')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'lf_banner',
            },
        ),
    ]
