# Generated by Django 2.2.1 on 2023-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231104_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img_url',
            field=models.ImageField(max_length=255, upload_to='banner', verbose_name='轮播图地址'),
        ),
    ]
